config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file,
  # see http://guides.rubyonrails.org/routing.html

  # get "exit", to: "sessions#destroy", as: :logout
  # This will create logout_path and logout_url as named helpers in your app
  # Calling logout_path will return /exit

  root "home#index"

  get "store", to: "store#index"
  get "admin", to: "admin#index"

  resources :carts
  resources :line_items, except: [:show]
  resources :orders

  scope "admin", as: "admin" do
    resources :products, except: [:show]
  end
end

app/models/order.rb
# frozen_string_literal: true

# Order model
class Order < ApplicationRecord
  enum pay_type: {
    "Check"          => 0,
    "Credit card"    => 1,
    "Purchase order" => 2
  }
  has_many :line_items, dependent: :destroy

  validates :name, :address, :email, presence: true
  validates :pay_type, inclusion: pay_types.keys

  def add_line_items_from_cart(cart)
    cart.line_items.each do |item|
      item.cart_id = nil
      line_items << item
    end
  end
end

app/controllers/orders_controller.rb
# frozen_string_literal: true

# orders Controller
class OrdersController < ApplicationController
  include CurrentCart
  before_action :set_cart, only: %i[new create]
  before_action :ensure_cart_isnt_empty, only: :new
  before_action :set_order, only: %i[show edit update destroy]

  # GET /orders
  def index
    @orders = Order.all
  end

  # GET /orders/1
  def show; end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit; end

  # POST /orders
  def create
    @order = Order.new(order_params)
    @order.add_line_items_from_cart(@cart)

    if @order.save
      Cart.destroy(session[:cart_id])
      session[:cart_id] = nil
      redirect_to store_url, notice: "Thank you for your order."
    else
      render :new
    end
  end

  # PATCH/PUT /orders/1
  def update
    if @order.update(order_params)
      redirect_to @order, notice: "Order was successfully updated."
    else
      render :edit
    end
  end

  # DELETE /orders/1
  def destroy
    @order.destroy
    redirect_to orders_url, notice: "Order was successfully destroyed."
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from internet, only allow the white list through
    def order_params
      params.require(:order).permit(:name, :address, :email, :pay_type)
    end

    def ensure_cart_isnt_empty
      return if @cart.line_items.any?

      redirect_to store_url, notice: "Your cart is empty"
    end
end

app/views/orders/_form.html.slim
= form_with(model: order, local: true) do |form|
  - if order.errors.any?
    div#error_explanation
      h2 #{pluralize(order.errors.count, "error")} prohibited this order from being saved:
      ul
      - order.errors.full_messages.each do |message|
        li = message

  div.field
    = form.label :name
    = form.text_field :name, id: :order_name, size: 40

  div.field
    = form.label :address
    = form.text_area :address, id: :order_address, rows: 3, cols: 40

  div.field
    = form.label :email
    = form.email_field :email, id: :order_email, size: 40

  div.field
    = form.label :pay_type
    = form.select :pay_type, Order.pay_types.keys, id: :order_pay_type,
                  prompt: 'Select a payment method'

  div.actions
    = form.submit 'Place Order'

app/views/orders/edit.html.slim
h1 Editing Order

= render 'form', order: @order

= link_to 'Show', @order
= link_to 'Back', orders_path

app/views/orders/index.html.slim
p#notice = notice

h1 Orders

table
  thead
    tr
      th Name
      th Address
      th Email
      th Pay type
      th colspan="3"

  tbody
    - @orders.each do |order|
      tr
        td = order.name
        td = order.address
        td = order.email
        td = order.pay_type
        td = link_to 'Show', order
        td = link_to 'Edit', edit_order_path(order)
        td = link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' }

br

= link_to 'New Order', new_order_path

app/views/orders/new.html.slim
/ <h1>New Order</h1>
/ <%= render 'form', order: @order %>
/ <%= link_to 'Back', orders_path %>

section.depot_form
  h1 Please Enter Your Details
  = render 'form', order: @order

app/views/orders/show.html.slim
p#notice = notice

p
  strong Name:
  = @order.name

p
  strong Address:
  = @order.address

p
  strong Email:
  = @order.email

p
  strong Pay type:
  = @order.pay_type

= link_to 'Edit', edit_order_path(@order)
= link_to 'Back', orders_path