config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file,
  # see http://guides.rubyonrails.org/routing.html

  # get "exit", to: "sessions#destroy", as: :logout
  # This will create logout_path and logout_url as named helpers in your app
  # Calling logout_path will return /exit

  root "home#index"

  get "store", to: "store#index"
  get "admin", to: "admin#index"

  resources :carts
  resources :line_items, except: [:show]
  resources :orders

  scope "admin", as: "admin" do
    resources :products, except: [:show]
  end
end

app/models/product.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: products
#
#  id          :integer          not null, primary key
#  name        :string           not null
#  description :text             not null
#  image_url   :string
#  price       :decimal(8, 2)    not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

# Product model
class Product < ApplicationRecord
  has_many :line_items, dependent: :restrict_with_error
  has_many :orders, through: :line_items

  # before_destroy :ensure_not_referenced_by_any_line_item

  validates :name,        presence: true, uniqueness: true
  validates :description, presence: true
  validates :image_url,   allow_blank: true,
                          format:      { with: /\.(gif|jpg|jpeg|png)\Z/i }
  validates :price,       presence:     true,
                          numericality: { greater_than_or_equal_to: 0.01 }

  private

    # ensure that there are no line items referencing this product
    def ensure_not_referenced_by_any_line_item
      return if line_items.empty?

      errors.add(:base, "Line Items present")
      throw :abort
    end
end

app/controllers/products_controller.rb
# frozen_string_literal: true

# Products Controller
class ProductsController < ApplicationController
  before_action :set_product, only: %i[edit update destroy]

  # GET /products
  def index
    @products = Product.all
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit; end

  # POST /products
  def create
    @product = Product.new(product_params)

    if @product.save
      redirect_to admin_products_url,
                  notice: "Product was successfully created."
    else
      render :new
    end
  end

  # PATCH/PUT /products/1
  def update
    if @product.update(product_params)
      redirect_to admin_products_url,
                  notice: "Product was successfully updated."
    else
      format.html { render :edit }
    end
  end

  # DELETE /products/1
  def destroy
    @product.destroy
    redirect_to admin_products_url,
                notice: "Product was successfully destroyed."
  end

  private ######################################################################

    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from internet, only allow the white list through
    def product_params
      params.require(:product).permit(:name, :description, :image_url, :price)
    end
end

app/helpers/products_helper.rb
# frozen_string_literal: true

# Products Helper
module ProductsHelper
  def asset_exists?(path)
    if Rails.configuration.assets.compile
      Rails.application.precompiled_assets.include? path
    else
      Rails.application.assets_manifest.assets[path].present?
    end
  end
end

app/views/products/_form.html.slim
= form_with(model: [:admin, @product], local: true) do |form|
  - if @product.errors.any?
    #error_explanation
      h2 #{pluralize(@product.errors.count, "error")} empêche l'enregistrement
      ul
        - @product.errors.full_messages.each do |message|
          li = message

  .form-group.row
    = form.label :name, class: "col-2 col-form-label"
    .col-sm-10
      = form.text_field :name, class: "form-control"

  .form-group.row
    = form.label :description, class: "col-2 col-form-label"
    .col-sm-10
      = form.text_area :description, rows: 10, cols: 60, class: "form-control"

  .form-group.row
    = form.label :image_url, class: "col-2 col-form-label"
    .col-sm-10
      = form.text_field :image_url, class: "form-control"

  .form-group.row
    = form.label :price, class: "col-2 col-form-label"
    .col-sm-10
      = form.text_field :price, class: "form-control"

  .row.justify-content-end
    = form.submit class: "btn btn-primary"

app/views/products/edit.html.slim
h1 Edition du produit

= render "form", store: @product

= link_to 'Back', admin_products_path

app/views/products/index.html.slim
br

.row.justify-content-center
  = link_to "🔙 Retour au centre d'administration", admin_path

br

p#notice = notice

.row.align-items-center
  .col
    h1 Liste des produits
  .col-md-auto
    = link_to "Nouveau produit", new_admin_product_path, class: "btn btn-primary"


.row
  - if @products.any?
    table.table.table-hover
      thead.thead-light
        tr
          th
          th Nom
          th Description
          th Prix
          th colspan="2"

      tbody
        - @products.each do |product|
          tr
            td = image_tag(product.image_url, height: "128") if asset_exists?(product.image_url)
            td.font-weight-bold = product.name
            td = product.description
            td.nowrap = number_to_currency(product.price)
            td = link_to 'Edit', edit_admin_product_path(product)
            td = link_to 'Destroy', \
                         admin_product_path(product), \
                         method: :delete, \
                         data: { confirm: "Cette action est irréversible !\nOn efface quand même ?" }
  - else

app/views/products/new.html.slim
h1 Nouveau produit

= render "form", store: @product

= link_to "Back", admin_products_path